In [1]:
import pandas as pd

In [2]:
SB = pd.read_csv("/sdd/Dubaoset/src/Phong/Source/addInput/evaluateSB.csv")

In [8]:
SF = pd.read_csv("/sdd/Dubaoset/src/Phong/Source/addInput/evaluateSF.csv")

In [9]:
RFE = pd.read_csv("/sdd/Dubaoset/src/Phong/Source/addInput/evaluateRFE.csv")

In [3]:
SB

     Unnamed: 0       feature  selected
0             0      B11B(10)      True
1            57  I2B-B16B(40)      True
2            71   WVB-IRB(60)      True
3            68   WVB-IRB(30)      True
4            66   WVB-IRB(10)      True
..          ...           ...       ...
115          82  WVB-B11B(50)     False
116          83  WVB-B11B(60)     False
117          33      B16B(40)     False
118          34      B16B(50)     False
119          87  WVB-B10B(40)     False

[120 rows x 3 columns]

In [5]:
SF

     Unnamed: 0        feature  selected
0             0       B11B(10)      True
1            66    WVB-IRB(10)      True
2            77       B09B(60)      True
3            76       B09B(50)      True
4            74       B09B(30)      True
..          ...            ...       ...
115          22       B14B(50)     False
116          83   WVB-B11B(60)     False
117          21       B14B(40)     False
118          20       B14B(30)     False
119         119  B12B-B14B(60)     False

[120 rows x 3 columns]

In [4]:
def takeRankValue(dataFrame):
    dictFeature = {}
    for idx, row in dataFrame.iterrows():
        name = row["feature"]
        band = name.split("(")[0]
        if band not in dictFeature:
            dictFeature[band] = 0
        else:
            dictFeature[band] += idx
    return dictFeature

In [5]:
dictFeature = takeRankValue(SB)
sortedSB = dict(sorted(dictFeature.items(), key= lambda x:x[1]))

In [6]:
dataFrameSB = pd.DataFrame(list(sortedSB.items()), columns= ["feature", "rank"])

In [7]:
dataFrameSB.head(20)

      feature  rank
0    I2B-B16B   122
1    IRB-B16B   177
2   B11B-B12B   196
3    B09B-IRB   242
4         IRB   247
5        B09B   282
6        B11B   283
7    WVB-B10B   307
8     WVB-IRB   312
9    B12B-IRB   325
10       B10B   325
11   WVB-B14B   340
12    WVB-I2B   368
13       B12B   379
14  B12B-B14B   415
15  B14B-B16B   421
16       B14B   422
17        I2B   473
18       B16B   489
19   WVB-B11B   491

In [10]:
dictSFFeature = takeRankValue(SF)

In [11]:
sortedSF = dict(sorted(dictSFFeature.items(), key= lambda x: x[1]))

In [12]:
dataFrameSF = pd.DataFrame(list(sortedSF.items()), columns= ["feature", "rank"])

In [13]:
dataFrameSF.head(20)

      feature  rank
0        B09B   128
1    IRB-B16B   145
2    I2B-B16B   160
3     WVB-IRB   239
4    WVB-B14B   262
5     WVB-I2B   295
6        B10B   306
7    B09B-IRB   311
8        B11B   321
9   B12B-B14B   339
10   WVB-B10B   342
11       B12B   344
12  B11B-B12B   351
13        I2B   368
14        IRB   372
15   B12B-IRB   400
16  B14B-B16B   440
17   WVB-B11B   449
18       B16B   462
19       B14B   551

In [14]:
dictREFFeature = takeRankValue(RFE)

In [17]:
sortRFE = dict(sorted(dictREFFeature.items(), key= lambda x: x[1] ))

In [18]:
dataFrameRFE = pd.DataFrame(sortRFE.items(), columns= ["feature", "rank"])

In [19]:
dataFrameRFE

      feature  rank
0        B10B   202
1    B12B-IRB   213
2        B11B   240
3    B09B-IRB   252
4    IRB-B16B   271
5    I2B-B16B   289
6     WVB-IRB   294
7   B11B-B12B   304
8    WVB-B10B   319
9     WVB-I2B   333
10   WVB-B11B   333
11  B14B-B16B   334
12  B12B-B14B   337
13       B12B   338
14       B09B   393
15   WVB-B14B   418
16        IRB   420
17       B16B   431
18       B14B   450
19        I2B   513

In [22]:
fullDataFrame = pd.merge(dataFrameRFE, dataFrameSB, on="feature", how="inner")
fullDataFrame = pd.merge(fullDataFrame, dataFrameSF, on="feature", how= "inner")

In [23]:
fullDataFrame

      feature  rank_x  rank_y  rank
0        B10B     202     325   306
1    B12B-IRB     213     325   400
2        B11B     240     283   321
3    B09B-IRB     252     242   311
4    IRB-B16B     271     177   145
5    I2B-B16B     289     122   160
6     WVB-IRB     294     312   239
7   B11B-B12B     304     196   351
8    WVB-B10B     319     307   342
9     WVB-I2B     333     368   295
10   WVB-B11B     333     491   449
11  B14B-B16B     334     421   440
12  B12B-B14B     337     415   339
13       B12B     338     379   344
14       B09B     393     282   128
15   WVB-B14B     418     340   262
16        IRB     420     247   372
17       B16B     431     489   462
18       B14B     450     422   551
19        I2B     513     473   368

In [24]:
fullDataFrame["Point"] = fullDataFrame["rank_x"] + fullDataFrame["rank_y"] + fullDataFrame["rank"]

In [25]:
fullDataFrame = (fullDataFrame.sort_values(by="Point").reset_index(drop=True))

In [26]:
top20 = fullDataFrame.head(20)

In [27]:
top20

      feature  rank_x  rank_y  rank  Point
0    I2B-B16B     289     122   160    571
1    IRB-B16B     271     177   145    593
2        B09B     393     282   128    803
3    B09B-IRB     252     242   311    805
4        B10B     202     325   306    833
5        B11B     240     283   321    844
6     WVB-IRB     294     312   239    845
7   B11B-B12B     304     196   351    851
8    B12B-IRB     213     325   400    938
9    WVB-B10B     319     307   342    968
10    WVB-I2B     333     368   295    996
11   WVB-B14B     418     340   262   1020
12        IRB     420     247   372   1039
13       B12B     338     379   344   1061
14  B12B-B14B     337     415   339   1091
15  B14B-B16B     334     421   440   1195
16   WVB-B11B     333     491   449   1273
17        I2B     513     473   368   1354
18       B16B     431     489   462   1382
19       B14B     450     422   551   1423

In [46]:
result = []
for idx, item in top20.iterrows():
    result.append(item["feature"])

In [47]:
result

['B11B',
 'IRB',
 'B12B',
 'B14B',
 'I2B',
 'B16B',
 'B10B',
 'B11B-B12B',
 'B12B-IRB',
 'I2B-B16B',
 'B14B-B16B',
 'WVB-IRB',
 'B09B',
 'WVB-B11B',
 'WVB-B10B',
 'WVB-B14B',
 'B09B-IRB',
 'WVB-I2B',
 'IRB-B16B',
 'B12B-B14B']